openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for user authentication and session management
paths:
  /api/v1/auth/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      description: Login a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_dos:
                  type: string
                institutional:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/auth/login:
    post:
      summary: Log in a user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '400':
          description: Invalid credentials
        '429':
          description: Too many login attempts
        '500':
          description: Internal server error

  /api/v1/auth/logout:
    post:
      summary: Log out the current user
      tags:
        - Auth
      responses:
        '200':
          description: User logged out successfully

  /api/v1/auth/verify:
    get:
      summary: Verify user authentication
      tags:
        - Auth
      responses:
        '200':
          description: User is authorized
        '401':
          description: Unauthorized

  /api/v1/auth/logins:
    get:
      summary: Get all login records
      tags:
        - Auth
      responses:
        '200':
          description: List of login records
        '500':
          description: Internal server error
